--- 
title: "Translating Natural Language Queries into SQL"
author: "Zayd Patel"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: report
classoption: openany
bibliography: [references.bib]
link-citations: yes
pagestyle: plain
colorlinks: true
geometry: "left=3cm,right=3cm,top=2.9cm,bottom=2.9cm"
description: "This paper describes the process of taking a natural language query and converting them into a structured language"
---

# Preface {-}

## Summary {-}

This paper takes a look at translating natural language queries into SQL queries in a domain specific environment; Retail. We look at an analytical and deep learning approach to this problem on a custom dataset with question deliberately written in such a way to test the approaches with a wide variety of SQL queries that use many different SQL operators. This paper found that for this specific domain, an analytical approach is not only more accurate, but less resources intensive and is more customisable making it easier to embed into other application

## Acknowledgements 

- This document is written using bookdown [@rstudioRstudioBookdown2020] as well as various R packages that Bookdown depends on.
- This document use a CSL style called `Cite Them Right 10th edition - Harvard` which is saved as the file `harvard.csl` [@zoteroZoteroStyleRepository].
- Project used Python 3.7 [@pythonsoftwarefoundationPythonDocumentation] and various other python packages which will be cited throughout the paper.
- Diagrams drawn with draw.io [@JgraphDrawio2020] and/or plantuml [@PlantumlPlantuml2020].
- Program of Study: **BSc (Hons) Computer Science**.
- Project Supervisor: **Dr Juilan Hough**.

## Abbreviations {#abbreviations}

- **SQL**: Structured Query Language
- **NLU**: Natural Query Understanding
- **CLI**: Command Line Interface
- **HTML**: HyperText Markup Language
- **ORM**: Object Relational Mapper
- **ERD**: Entity Relationship Diagram
- **LSTM**: Long Short Term Memory
- **API**: Application Programming Interface
- **REST**: REpresentational State Transfer
- **JSON**: JavaScript Object Notation




## Definitions {#definitions}

- **Database**: A structured set of data held in a computer that is accessible in various ways.
- **ORM**: Object/Relational Mapping (ORM) provides a *methodology and mechanism for object-oriented systems to hold their long-term data safely in a database, with transactional control over it, yet have it expressed when needed in program objects* [@oneilObjectRelationalMapping2008]. 
- **ERD**: An ERD is a *data model used to describe the relationship between different entities including the different attributes of each entity* [@chenEntityrelationshipModelUnified1976].
- **Reinforcement Learning**: A type of Artificial Intelligence where by artificial agents learn for themselves through trial and error by being rewarded for successful strategies and punished by unsuccessful strategies [@silverDeepReinforcementLearning2016].
- **Neural Network**: Neural Networks are a way of doing machine learning by analysing hand labeled training examples. Neural Networks are loosely modelled on the human brain as they consist of nodes, usually organised into layers, that feed into other nodes. Each individual node is adjusted until the final layer of nodes, also known as the output layer, correctly outputs data as expected in accordance to the labeled training data. [@hardestyExplainedNeuralNetworks2017].
- **Relational Database**: A relational Database is type of database where the data is organised into tables which can then be linked or *related* to each other. For example, you can have a table with customer details and a table with order details and you can implement a relationship between those two tables and extract new pieces of information - for example, you can run a query which shows all the customers that have ordered more than 5 products.[@ibmcloudeducationRelationaldatabases2019]
- **Stop Words**: Stop words are words that appear to be of little value and are excluded from the vocabulary [@manningIntroductionInformationRetrieval2008]. 
- **Part of Speech tagging**: Part of speech tagging is the process of taking some text and breaking it down into their parts of speech. [@nlpStanfordNaturalLanguage]
- **Python Virtual Environment**: Python virtual environments are used to create self contained, isolated versions of python that allow you to install external python packages and modules without affecting other python installations. For example, *"If application A needs version 1.0 of a particular module but application B needs version 2.0, then the requirements are in conflict and installing either version 1.0 or 2.0 will leave one application unable to run."* Each application will have its own virtual environment and can exist simultaneously [@pythonsoftwarefoundation12VirtualEnvironments]. 
- **Semantic Parsing**: *" Semantic parsing is the task of translating natural language utterances to (often machine executable) formal meaning representations"*
- **LSTM**: *"LSTMs are a way of storing information over extended time intervals by recurrent backpropogation."* Before, the introduction of LSTMs, recurrent backpropogation took long periods of time mostly because of insufficient, decaying error backflow [@hochreiterLongShortTermMemory1997].
- **REST API**: Uses the HTTP protocol to transfer a resource and its state through HTTP protocols [@mozilladevelopernetworkDefinitionREST]
- **Docker Container**: *"A container is a standard unit of software that packages up code and all its dependencies so the application runs quickly and reliably from one computing environment to another."* [@dockerWhatContainerApp]